
states = {	'AL': 'Alabama',
			'AZ': 'Arizona',
			'CO': 'Colorado',
			'FL': 'Florida',
			'IL': 'Illinois',
			'MD': 'Maryland',
			'MI': 'Michigan',
			'NC': 'North Carolina',
			'OH': 'Ohio',
			'PA': 'Pennsylvania',
			'TX': 'Texas',
			'VA': 'Virginia',
			'WI': 'Wisconsin',
			}
